### ISSUE TITLE
Add SecureString for SendingEmails

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWinReporting#1]

**Comment by PrzemyslawKlys** [comment]
I think I already added it. I've added support to it via PSSharedGoods. It works in several ways.

    EmailServer                 = "smtp.office365.com"
    EmailServerPassword         = "YourPassword"
    EmailServerPasswordAsSecure = $false
    EmailServerPasswordFromFile = $false

Why do you want to change it? I understand renaming fields thou as it's unnecessary to keep EmailServer in the name.

**Comment by PrzemyslawKlys** [comment]
You can use Password in plain text, if you use AsSecure True it expects it to be secure string, and if from file it expects secure string in File. I actually created this little project that allows for quick creation of those:

https://github.com/EvotecIT/PSMyPassword

**Comment by snd3r** [comment]
I would like to simplify the following function:
https://github.com/EvotecIT/PSSharedGoods/blob/master/Public/Connectivity/Request-Credentials.ps1

I would like to see her like this:
```powershell
function Request-Credentials {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string] $UserName,
        [Parameter(Mandatory = $true, ParameterSetName = 'PasswordFromSecureString')]
        [SecureString] $Password,
        [Parameter(Mandatory = $true, ParameterSetName = 'PlainTextPassword')]
        [string] $PlainTextPassword,
        [Parameter(Mandatory = $true, ParameterSetName = 'PasswordFromFile')]
        [string] $PasswordFile,
        [switch] $NetworkCredentials
    )

    switch ($PSCmdlet.ParameterSetName) {
        'PlainTextPassword' {
            Write-Warning 'Please do not use passwords in plain-text'
            $SecurePassword = $PlainTextPassword | ConvertTo-SecureString -AsPlainText -Force
        }
        'PasswordFromSecureString' {
            $SecurePassword = $Password | ConvertTo-SecureString
        }
        'PasswordFromFile'{
            $SecurePassword = Get-Content $PasswordFile | ConvertTo-SecureString
        }
    }
    $Credentials = New-Object System.Management.Automation.PSCredential($UserName, $SecurePassword)
    if ($NetworkCredentials) {
        $Credentials = $Credentials.GetNetworkCredential()
    }
    return $Credentials
}
```

**Comment by PrzemyslawKlys** [comment]
As long as it will keep its functionality and won't break existing scripts it's fine to optimize. I'm afraid thou that this change will break other scripts as well that are already using this.
