### ISSUE TITLE
ErrorAction Stop stopping on non-critical errors

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWinReporting#23]
@snd3r 

![image](https://user-images.githubusercontent.com/15063294/47904399-5bfb1b80-de85-11e8-9e4c-532caee10dee.png)

Your setting did this. I guess one must go now thru every possible scenario and fix Try/Catch errors with this one. Get-WinEvent is very weird in that if there's no events found it will throw error (I would expect it to not do that). Please add some logic to it then.

**Comment by PrzemyslawKlys** [comment]
@snd3r will you fix this? Or should I?

**Comment by PrzemyslawKlys** [comment]
@snd3r  How is it going?

**Comment by snd3r** [comment]
Is the problem relevant?

**Comment by PrzemyslawKlys** [comment]
Not anymore I think. Works as required.
