### ISSUE TITLE
Set-EmailFormatting breaks CSS

### ISSUE THREAD

**Issue by snd3r** [EvotecIT/PSWinReporting#28]
In the HTML report generation code, the first step is adding css by Set-EmailHead:

https://github.com/EvotecIT/PSWinReporting/blob/ec1e6eef3b3df43524f6744fdbbcb25778c3ab6d/Private/Start-Report.ps1#L89

The next stage is html post-processing by Set-EmailFormatting cmdlet.
In one of the stages, <bt> tag is added to each line:
```powershell
    foreach ($t in $Template) {
        $Body += "$t<br>"
    }
```
https://github.com/EvotecIT/PSSharedGoods/blob/d53ed6be933b307651a44c32362917056aae0f5d/Public/Email/Set-EmailFormatting.ps1#L18

After this, the style sheet code becomes broken:
![default](https://user-images.githubusercontent.com/13349072/48899209-cc87cd80-ee70-11e8-90e0-1e9aa74d6ebf.png)

I think we should skip the styles section as a workaround.

**Comment by PrzemyslawKlys** [comment]
Thanks for reporting this. I'll take a look and fix this. It's used all over place in my other scripts I believe

**Comment by PrzemyslawKlys** [comment]
@snd3r  there is one more thing about that function and probably other functions. Usage of Write-Color which is replaced with Add Logger of yours and that function is shared with other projects ;)

**Comment by snd3r** [comment]
@PrzemyslawKlys I understand it.
The principle of "Do not repeat yourself" is a good principle, but sometimes it can play a bad joke by make a combinatorial explosion of checks on the correctness of work in all places.

**Comment by PrzemyslawKlys** [comment]
Well make a [switch] UseLogger and modify it so that old version works the way it does, and add a logger to it? I don't see any other choice until other programs are migrated to the same approach.

**Comment by PrzemyslawKlys** [comment]
On first look seems ok. Will test it later today. Just to say I really enjoy working with you :-) It's much much better when you have someone else working on the same project and helping you out!

**Comment by PrzemyslawKlys** [comment]
I have to investigate this issue further. Have to revert the change due to PSPasswordExpiryNotifications loosing some page <BR>.

**Comment by snd3r** [comment]
@PrzemyslawKlys can you provide the raw html with which the problem occurs?

**Comment by PrzemyslawKlys** [comment]
Yes.

![image](https://user-images.githubusercontent.com/15063294/50958247-8ccc8200-14c0-11e9-875b-ece8de014e9f.png)


```html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style>
        BODY {
            background-color: white;
            font-family: Calibri Light;
            font-size: 9pt;
        }

        TABLE {
            border-width: 1px;
            border-style: solid;
            border-color: black;
            border-collapse: collapse;
            font-family: Calibri Light;
            font-size: 9pt;
        }

        TH {
            border-width: 1px;
            padding: 3px;
            border-style: solid;
            border-color: black;
            background-color: #00297A;
            color: white;
            font-family: Calibri Light;
            font-size: 9pt;
        }
        TR {
            font-family: Calibri Light;
            font-size: 9pt;
        }

        UL {
            font-family: Calibri Light;
            font-size: 9pt;
        }

        LI {
            font-family: Calibri Light;
            font-size: 9pt;
        }

        TD {
            border-width: 1px;
            padding-right: 2px;
            padding-left: 2px;
            padding-top: 0px;
            padding-bottom: 0px;
            border-style: solid;
            border-color: black;
            background-color: white;
            font-family: Calibri Light;
            font-size: 9pt;
        }

        H2 {
            font-family: Calibri Light;
            font-size: 12pt;
        }

        P {
            font-family: Calibri Light;
            font-size: 9pt;
        }
        * {
            font-family: Calibri Light;
            font-size: 9pt;
        }
    </style><a style="text-decoration:none" href="https://evotec.xyz" class="clink logo-container"><img width="200" src="https://evotec.xyz/wp-content/uploads/2015/05/Logo-evotec-012.png" border="0" class="company-logo" alt="company-logo"></a>
<br>    Hello <b>Test Przemyslaw Klys</b>,
    Your <i>password</i> is due to expire in 42 days.

<br>    To change your <i>password</i>:
<br>    - press <span style="color:Blue">CTRL&#43;ALT&#43;DEL</span> -&gt; Change a <i>password</i>...
<br>
<br>    If you have forgotten you <i>password</i> and need to <span style="color:Red">reset it</span>, you can do this by <span style="color:Red"><a href="https://passwordreset.microsoftonline.com/">clicking here</a></span>
    In case of problems <span style="color:Blue">please contact</span> HelpDesk by <span style="color:Red"><a href="https://evotec.xyz">visiting Service Desk Portal</a></span> or by sending an email to <span style="color:Red"><a href="mailto:helpdesk@domain.pl?subject=I need help with my password">Service Desk</a></span>.

<br>    Alternatively you can always call Service Desk at <span style="color:Green">&#43;48 22 600 20 20</span>
<br>
<br>    Kind regards,
<br>    Evotec IT<br>
```

And the template was like this:

```
    Template = "
    Hello <<DisplayName>>,
    Your password is due to expire in <<TimeToExpire>> days.

    To change your password:
    - press CTRL+ALT+DEL -> Change a password...

    If you have forgotten your password and need to reset it, you can do this by <<ClickingHere>>
    In case of problems please contact HelpDesk by <<VisitingPortal>> or by sending an email to <<ServiceDeskEmail>>.

    Alternatively, you can always call Service Desk at +48 22 600 20 20

    Kind regards,
    Evotec IT"
```

![image](https://user-images.githubusercontent.com/15063294/50958222-7aeadf00-14c0-11e9-93ea-8e03a12443dd.png)


So it skipped adding BR for some cases in a template. It was supposed to look like this:

![image](https://user-images.githubusercontent.com/15063294/50958334-bdacb700-14c0-11e9-87bf-2195d97ae5ab.png)


I've actually fixed some issues with it as well where I've noticed that I've not added <body> tag at all which meant font wouldn't be applied correectly if there was no <p> tag. 

I was thinking that it's possible to just merge 3 functions into 1 and treat styles separately to fix your issue (I've not seen it myself thou) and skip trying to work with a workaround.

**Comment by snd3r** [comment]
> But do you still get the problem of in styles?
Yes, i do.
If I want to define styles in a template, I get broken code:
![default](https://user-images.githubusercontent.com/13349072/51536759-6dddd080-1e6e-11e9-808a-8b5e42dc22be.png)

Not the latest git version of the PSWinReporting works in my infrastructure, but looking on the code, I see no reason why the behavior should change. The stage of formatting the template is still after the stage of adding the head section.

**Comment by PrzemyslawKlys** [comment]
Most of it is in PSSharedGoods. Also, what do you mean if you want to define styles in a template?

**Comment by snd3r** [comment]
Never mind.
I updated both modules from the git and I see a problem again, what am I doing wrong?

![default](https://user-images.githubusercontent.com/13349072/51583820-2ef25e00-1ef4-11e9-9726-249d3a79b639.png)

**Comment by PrzemyslawKlys** [comment]
I am not sure how this ended up in here as I wasn't experiencing this. Now that I had some time, I had same issue and I've now fixed it. I've yet some work to be done but that should fix it (assuming you use up to date PSSharedGoods and PSWinReporting.

**Comment by snd3r** [comment]
I like this approach
