### ISSUE TITLE
Unable to get Security Log Size

### ISSUE THREAD

**Issue by beems** [EvotecIT/PSWinReporting#30]
Thank you for probably the most useful Powershell scripts I've ever used. 

The following errors are seen when the script goes to pull the log size for the Security log on just one of the servers. The log sizes for other logs on the same server are reported successfully, and the security logs on other servers are reported on successfully.

`get-WinEvent : Could not retrieve information about the Security log. Error: Attempted to perform an unauthorized operation..
At C:\Program Files\WindowsPowerShell\Modules\PSWinReporting\1.7.3\Private\Get-EventLogSize.ps1:5 char:23
+ ...   $result = get-WinEvent -ListLog $LogName -ComputerName $server | Se ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : LogInfoUnavailable,Microsoft.PowerShell.Commands.GetWinEventCommand
 
get-WinEvent : There is not an event log on the DC1.local.domain.com computer that matches "Security".
At C:\Program Files\WindowsPowerShell\Modules\PSWinReporting\1.7.3\Private\Get-EventLogSize.ps1:5 char:23
+ ...   $result = get-WinEvent -ListLog $LogName -ComputerName $server | Se ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingLogsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
 `

Any idea what I should look at to see if we can get that working?

**Comment by PrzemyslawKlys** [comment]
Which permissions your account has when you run this script?

**Comment by beems** [comment]
The account is running with "Domain Administrator" privileges.

**Comment by PrzemyslawKlys** [comment]
```
Get-WinEvent -ListLog Security -ComputerName YOURDC
```
does that works?

**Comment by beems** [comment]
I think you may be able to close this. I created an account for this to run under as a scheduled task, but I didn't log out to allow the group membership status to apply. After logging the account out, it was able to pull the security log from the currently-logged-on server successfully.

**Comment by PrzemyslawKlys** [comment]
Btw, I guess you've not seen my other most useful scripts *hint* PSWinDocumentation.
