### ISSUE TITLE
"happend" and "occured" misspelled in reports

### ISSUE THREAD

**Issue by beems** [EvotecIT/PSWinReporting#32]
In multiple locations in at least the email-based reporting, the word "happened" is misspelled as "happend", and in at least one location "occurred" is misspelled as "occured"

Examples:
No changes **happend** during that period.
The membership of those groups below has changed
No changes **happend** during that period.
Following group creation/deletion **occured**
No changes **happend** during that period.
Following GPOs were modified
No changes **happend** during that period.

**Comment by PrzemyslawKlys** [comment]
I could probably release new version as -PreRelease. But you would need to use new config (small updates).
