### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by louissanchez84** [EvotecIT/PSWinReporting#41]
Hi, 

I'm not really new to PowerShell, I consider myself fairly knowledgeable, but have no idea how to configure this. Would it be possible to create a true getting started guide? I just want to monitor group membership, but could see many of these reporting components being helpful.

**Comment by PrzemyslawKlys** [comment]
There are many guides to this. 

Your starting point: https://evotec.xyz/hub/scripts/pswinreporting-powershell-module/

And then read all those:
![image](https://user-images.githubusercontent.com/15063294/54437552-291b3b00-4735-11e9-8f95-3dc67512e7e7.png)

Basically, you can 

```
Install-Module PSWinReporting
Install-Module PSWriteColor
Install-Module PSEventViewer
Install-Module PSWriteExcel
Install-Module PSSharedGoods
```

Copy config from the newest article: https://evotec.xyz/pswinreporting-1-8-split-of-branches-legacy-vs-new-hope/ disable SQL on it and run it. But you really should read thru all those articles as they have bits and pieces that will get you started. For sure you need audit events enabled in your AD environment.

**Comment by PrzemyslawKlys** [comment]
Also, keep in mind that you should avoid using the GitHub version from Master branch because it has no documentation and has bugs.
