### ISSUE TITLE
Add 'credentials' switch

### ISSUE THREAD

**Issue by progenyofeniac** [EvotecIT/PSWinReporting#46]
It would be helpful to have the option to specify credentials when running the module so as to gather logs from domain controllers while running the module as a standard user.

**Comment by WinterJackSolutions** [comment]
Seconded on this - struggling to get it working running as domain admin account from local machine. Thx

**Comment by PrzemyslawKlys** [comment]
I'll make this happen. Need to make some tests with PSEventViewer - as this is basically a feature that will end up in https://github.com/EvotecIT/PSEventViewer and PSWinReporting will wrap it up.

**Comment by PrzemyslawKlys** [comment]
Will be in 2.0.10

**Comment by PrzemyslawKlys** [comment]
Added, released

```
Update-Module PSWinReportingV2
```

Please test and report back if things won't work. Thanks
