### ISSUE TITLE
Prerequisites for reporting

### ISSUE THREAD

**Issue by z442a9** [EvotecIT/PSWinReporting#5]
Hi,

This is very very nice script and thanks for this! Maybe I missed but is there a documentation what I need to configure in my DC logging settings before I start using this?

**Comment by PrzemyslawKlys** [comment]
Just a GPO over your DC.
![image](https://user-images.githubusercontent.com/15063294/42310265-40eede42-803b-11e8-834a-d1f2f0153bb5.png)

You can skip the logon/logoffs as those most likely will not be useful. Seeing as logs are overloaded with those your Security log will grow a lot and you won't have much benefits from this. 

It still can be useful for other purposes. The other GPO would be:

![image](https://user-images.githubusercontent.com/15063294/42310343-78f68a74-803b-11e8-93e4-4add4f884e09.png)


So the size of the logs is controlled. Keep in mind on above screenshot the log size is very small. You may need to adjust this to your environment.

**Comment by z442a9** [comment]
Thanks!
