### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by tgallagher12** [EvotecIT/PSWinReporting#6]
PSWordMain.ps1 is returning the below error when running.

-------------------------------------

"Exception calling "SaveAs" with "1" Argument(s): "Access to the path 'C:\Users\%username%\Desktop' is denied." At C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\0.4.8.1\Public\PSWordMain.ps1:49 char:9

+ $WordDocument.SaveAs($filepath)
+ CategoryInfo NotSpecified (:) [] MethodInvocationException
+ FullyQualifiedErrorId : UnauthorizedAccessException

-------------------------------------

Figured it was just a permissions issue, so I ran it through PsExec as system and that still returned the same error. Tried to edit PSWordMain to save instead of saveas, but I'm sure I did it wrong, because it still didn't work.

**Comment by PrzemyslawKlys** [comment]
Are you sure it's about PSWinReporting and not PSWinDocumentaiton? PSWinReporting doesn't use PSWriteWord. But to answer your question  'C:\Users%username%\Desktop'  is used for some reason. This is not a valid path. Just make sure to type it in by hand C:\Users\yourname\Desktop\myfile.docx ?

**Comment by tgallagher12** [comment]
Naturally I had both of your repositories open and submitted on the wrong one haha. Looks like it was an issue with the filepath! Thanks!
