### ISSUE TITLE
Error - no events were found that match for version 1.8.1.5

### ISSUE THREAD

**Issue by verkruemelt** [EvotecIT/PSWinReporting#60]
![error](https://user-images.githubusercontent.com/1926264/73723240-dc639880-4728-11ea-8e1e-b68e1137f9b0.PNG)

**Comment by PrzemyslawKlys** [comment]
Tnx for reporting. Will be fixed.

**Comment by PrzemyslawKlys** [comment]
But just so you know - this one seems like checking for events doesnt work for you. As far as i read the screenshot this code checks for a single event in log to see dates between each the log has logs. And in your case it fails so probably nothing to read which is weird. I’ll fix it to not error out but you should make sure you have access.

**Comment by verkruemelt** [comment]
I've tried with dom-admin directly on DC in elevated PS-Console.

Expected reports:
Changed Group Membership
Deleted Group

**Comment by PrzemyslawKlys** [comment]
Well did you actually enable auditing? They don't come by default.

**Comment by verkruemelt** [comment]
Auditing was the problem. Thank you!
The error message still appears, but now I get events in the report. :)

**Comment by PrzemyslawKlys** [comment]
I still need to fix it :-)
