### ISSUE TITLE
Domain Controller requirements?

### ISSUE THREAD

**Issue by brimur** [EvotecIT/PSWinReporting#61]
Hi, sorry if I missed this but what is the method your module uses to access the domain controllers? I could not find the requirements for the domain controllers. Is something like psremoting required? The domain controllers in our environment do not have psremoting and we cannot install anything on them so I wanted to verify before trying it out. Thanks

**Comment by PrzemyslawKlys** [comment]
The easiest way to test is to use Get-WinEvent to access Security log. If you can do that PSwinReporting will work.
