### ISSUE TITLE
Unable to install onto AzureVM

### ISSUE THREAD

**Issue by McGreggin** [EvotecIT/PSWinReporting#64]
Attempting to install onto AzureVM to run but results in the following:

PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'PSWinReportingV2'. Try
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by McGreggin** [comment]
I've went through the process of .nupkg so will close

**Comment by PrzemyslawKlys** [comment]
It's most likely related to this one: https://evotec.xyz/powershellgallery-disables-support-for-tls-1-0-breaking-install-module/

**Comment by PrzemyslawKlys** [comment]
Alternatively check that Get-PSRepository has PSGallery.
