### ISSUE TITLE
report highlighting with ad in german language

### ISSUE THREAD

**Issue by Secarius** [EvotecIT/PSWinReporting#65]
Hello,

thank you for this wonderful PS Module.

I have a small question:

as my dc language is german, i have no highlightning in the reports.
i think, thats because you use trigger words like "changed" "added" ...

Further down, ill attach some screenshots. Is it possible to configure those triggers in the config file?
![1](https://user-images.githubusercontent.com/777486/124612300-81c8f180-de72-11eb-8736-8b7bdb6ecc34.png)
![2](https://user-images.githubusercontent.com/777486/124612304-82618800-de72-11eb-8838-ba3a69d1eb1b.png)
![3](https://user-images.githubusercontent.com/777486/124612306-82fa1e80-de72-11eb-841a-6c836dbda794.png)
![4](https://user-images.githubusercontent.com/777486/124612308-82fa1e80-de72-11eb-974d-d5c710dcaa56.png)

Kind Regards
Felix

**Comment by PrzemyslawKlys** [comment]
Which version are you using?

**Comment by Secarius** [comment]
I just installed the modules via PowerShellGallery
and used the config from: https://evotec.xyz/hub/scripts/pswinreporting-powershell-module/

**Comment by Secarius** [comment]
I did the following install:

Install-Module PSWinReporting
Install-Module PSWriteColor
Install-Module PSEventViewer
Install-Module PSWriteExcel
Install-Module PSSharedGoods

**Comment by PrzemyslawKlys** [comment]
Then changing colors here will fix it no?

```
    Colors                 = @{
        # case sensitive
        Red   = 'removed', 'deleted', 'locked out', 'lockouts', 'disabled', 'Domain Admins', 'was cleared'
        Blue  = 'changed', 'changes', 'change', 'reset'
        Green = 'added', 'enabled', 'unlocked', 'created'
    }
```

**Comment by Secarius** [comment]
thx i think i am blind 🙈 
ill test it tomorrow

**Comment by Secarius** [comment]
ive change the settings like this
`    Colors                 = @{
        # case sensitive
        Red   = 'removed', 'deleted', 'locked out', 'lockouts', 'disabled', 'Domain Admins', 'was cleared', 'gelöscht', 'entfernt', 'gesperrt', 'deaktiviert', 'gelöscht', 'zurückzusetzen'
        Blue  = 'changed', 'changes', 'change', 'reset', 'geändert'
        Green = 'added', 'enabled', 'unlocked', 'created', 'aktiviert', 'erstellt'
    }`

But it will not work with words containing  `ä ö ü`
![image](https://user-images.githubusercontent.com/777486/124707973-d9f70680-def9-11eb-81cd-af3caac80d53.png)

and it doesent work with "aktiviert" and "deaktiviert"
deaktiviert is now multicolor
![image](https://user-images.githubusercontent.com/777486/124707912-c9469080-def9-11eb-8a60-f384b79c9b06.png)

**Comment by PrzemyslawKlys** [comment]
Try using " aktiviert".

**Comment by Secarius** [comment]
```
    Colors                 = @{
        # case sensitive
        Red   = 'removed', 'deleted', 'locked out', 'lockouts', 'disabled', 'Domain Admins', 'was cleared', 'gelöscht', 'entfernt', 'gesperrt', 'deaktiviert', 'aktiviert', 'gelöscht', 'zurückzusetzen'
        Blue  = 'changed', 'changes', 'change', 'reset', 'geändert'
        Green = 'added', 'enabled', 'unlocked', 'created', 'aktiviert', 'erstellt'
    }
```
still gives 
![image](https://user-images.githubusercontent.com/777486/124711334-3d833300-defe-11eb-96ea-7a0a6de1078b.png)
![image](https://user-images.githubusercontent.com/777486/124711359-4411aa80-defe-11eb-8a69-50e4e6a9a218.png)

**Comment by PrzemyslawKlys** [comment]
I mean use space to make sure it's treated as a separate word.

**Comment by Secarius** [comment]
That worked 👍 

Do you have a solution (escapeing) for the `ö ü ä` ?

**Comment by PrzemyslawKlys** [comment]
Save HTML that you have in email to desktop, open the file up, search for the word and see if it's not written in HTML equivalent rather then how you wrote it. Use that instead.

**Comment by Secarius** [comment]
that did the trick: `'zur&#252;ckzusetzen',`

**Comment by Secarius** [comment]
Do you have a idea how to fix this?
Warnings:
Security log on **** **doesn't cover whole date range requested. Oldest event 07/06/2021 16:43:02** while requested 07/06/2021 00:00:00.

I have the log set to 4gb

![image](https://user-images.githubusercontent.com/777486/124716424-5abb0000-df04-11eb-8758-cbd1f4e53189.png)

**Comment by PrzemyslawKlys** [comment]
Either you have high amount of logs and things keep overwritting or something is not right. What domain size you have?

**Comment by Secarius** [comment]
Whats do you mean with domain size?
around 40 clients and 30server
i get a lot of 4662 IDs Object read
mostly the server asking for its access group

**Comment by PrzemyslawKlys** [comment]
Maybe you should revisit what logs you have enabled in AD and adjust it. Some logs are not worth gathering. Alternatively you can se up pswinreporting in forwarding mode and choose events it monitors and use a single server for gahering logs from all dcs

**Comment by Secarius** [comment]
Do you have a example, wich logs are good to be enabled?

**Comment by PrzemyslawKlys** [comment]
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations
