### ISSUE TITLE
Event ID 4722 (enabled), 4725 (disabled), 4726 (deleted) are not visible in the output file

### ISSUE THREAD

**Issue by Mumprecht** [EvotecIT/PSWinReporting#67]
I run the script with the paramter -report ADUserChanges. I see only the log entries with the EventID 4720 and 4738. Do I use the wrong key parameter?
Kindly
Urs

**Comment by PrzemyslawKlys** [comment]
ADUserStatus -> Events  = 4722, 4725, 4767, 4723, 4724, 4726
ADUserChanges -> Events =  4720, 4738
