### ISSUE TITLE
Send notifications to people in ManagedBy fields

### ISSUE THREAD

**Issue by pompushko** [EvotecIT/PSWinReporting#7]
Hello developer :)

May be merge with Monitor-ADGroupMembership and try monitor groups separately?

**Comment by PrzemyslawKlys** [comment]
What benefit you’re looking for?

**Comment by PrzemyslawKlys** [comment]
Is that person in ManagedBy field?

**Comment by pompushko** [comment]
Yes Przemyslaw :)

**Comment by PrzemyslawKlys** [comment]
Then that is your feature request, anything else?

**Comment by PrzemyslawKlys** [comment]
You can achieve this in PSWinReportingV2 using FInd-Events command. Feel free to utilize that. It should be trivial to write a wrapper around that.
