### ISSUE TITLE
Format-TransposeTable Error

### ISSUE THREAD

**Issue by judson76** [EvotecIT/PSWinReporting#85]
I created a config/script file (based on the post [here](https://evotec.xyz/hub/scripts/pswinreporting-powershell-module/)) and changed the parameters to match my environment. When I run, I am getting the following error:

[2024-08-22 09:15:52] [i] Establishing servers list to process...
Format-TransposeTable : A positional parameter cannot be found that accepts argument 'System.Object[]'.
At C:\Program Files\WindowsPowerShell\Modules\PSWinReporting\1.8.1.6\PSWinReporting.psm1:343 char:12
     return Format-TransposeTable $DCs
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Format-TransposeTable], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Format-TransposeTable

**Comment by PrzemyslawKlys** [comment]
It's hard to say without seeing the config. I guess I really need to release version 3 to simplify setup and functionality

**Comment by judson76** [comment]
I've been tinkering with V2 and was able to get it to run successfully.

**Comment by sgruber94** [comment]
I Identifed the issue on the Legacy branch we need to change the Line47 from return `Format-TransposeTable $DC` to   `return Format-TransposeTable $DC -Legacy`
[https://github.com/EvotecIT/PSWinReporting/blob/Legacy/Private/Get-DC.ps1#L47](https://github.com/EvotecIT/PSWinReporting/blob/Legacy/Private/Get-DC.ps1#L47)

I Saw this change connecting from the PSGoods rewrites introduced in Version v0.0.292
with Version v0.0.291 its working fine

**Comment by PrzemyslawKlys** [comment]
Nice catch, I did change how things work because I added new ability to PSWriteHTML. I guess I need to rerelease V1/V2 with all changes incorporated + work on V3... thank you
